version: '1'
services:
  myapp:
    image: anudinaorg/site-services:latest
    build:
      context: ./
      dockerfile: Dockerfile
    
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/opt/app/logs